name: flutter_sahaayak
description: A next-generation AI assistant for rural India.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  lottie: ^2.7.0
  flutter_animate: ^4.5.0
  flutter_tts: ^4.2.2
  speech_to_text: ^7.0.0
  permission_handler: ^11.3.1
  record: ^6.2.0
  path_provider: ^2.1.5
  uuid: ^4.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
